"""Notifications history - created at

Revision ID: ece1f7f09878
Revises: 6a025a1ace14
Create Date: 2026-01-19 03:11:08.634817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ece1f7f09878'
down_revision: Union[str, Sequence[str], None] = '6a025a1ace14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications_history_records', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications_history_records', 'created_at')
    # ### end Alembic commands ###
